### ISSUE TITLE
Extract color from the song background

### ISSUE THREAD

**Issue by CaptSiro** [Team-BTMC/osu-radio#20]

**Comment by CaptSiro** [comment]
I would like to take on this issue. I am going to reuse code (rewrite it in Typescript) from my repo:
https://github.com/CaptSiro/prominent-color

Examples of extracted colors (background color of +):
![Image](https://github.com/user-attachments/assets/07bd35be-4298-4704-aaee-c924a15c9ceb)
![Image](https://github.com/user-attachments/assets/c200002c-7373-4149-b4d9-e5fb6bd92dad)
![Image](https://github.com/user-attachments/assets/4e9919f0-b7d1-4cc4-922d-9d1ac204337c)

**Comment by uzervlad** [comment]
There already are multiple libraries for that on NPM (e.g. [extract-colors](https://www.npmjs.com/package/extract-colors) and [color-thief](https://www.npmjs.com/package/color-thief)), I'm not sure this needs yet another solution unless there are significant benefits

**Comment by SrIzan10** [comment]
what might this be for?
