### ISSUE TITLE
Redesign osu directory select scene

### ISSUE THREAD

**Issue by CaptSiro** [Team-BTMC/osu-radio#23]
This is what we are working with:
![image](https://github.com/user-attachments/assets/7f3bc7ed-49ba-4307-b2a0-fd5dae981b62)
![image](https://github.com/user-attachments/assets/7704d00d-a656-4775-b023-8ef43d110aed)

figma link for design we are striving for 
https://www.figma.com/design/tNBJr7TlEsoWsWdAewqoUg/osu!-radio?node-id=0-1&t=XtwvnqbnICGtLk9y-1

**Comment by EvenMasait** [comment]
![image](https://github.com/user-attachments/assets/d50609d9-9ad2-4dbf-9da1-45d9369714e7)
hows this

**Comment by CaptSiro** [comment]
Yes, the app should have a setting to redo the import. But I would like to have an initial import fullscreen. Something like osu!lazer does. You are greeted with the setup wizard after installing and after finishing it you can rerun the setup wizard. This is looking good though. It is just not the thing I was after. We could take the individual components out of this design:
- select
- button with icon (multicolored)
