### ISSUE TITLE
Tracks doesn't have BG covers on Linux version

### ISSUE THREAD

**Issue by kartavkun** [Team-BTMC/osu-radio#35]
I use db branch and tracks doesn't have the covers. I dunno about windows. Maybe it works fine in Win, but on Linux it don't work fine

![image](https://github.com/user-attachments/assets/87cab07b-d26a-407d-a62d-ad6904803a41)

**Comment by kartavkun** [comment]
Master branch fixed thsi issue

**Comment by brw** [comment]
Yea I know I was the one who fixed it lol
