### ISSUE TITLE
Increase hit box on song seek bar

### ISSUE THREAD

**Issue by CaptSiro** [Team-BTMC/osu-radio#57]
The current implementation reacts to the user clicking slightly above the bar

(each time mouse stops is a click)
https://github.com/user-attachments/assets/34d2e59e-3331-4ba0-8730-4a68a681b56e

**Comment by SrIzan10** [comment]
how well is this after pr #58 @Tnixc ?

**Comment by Tnixc** [comment]
#58 doesn't change anything about this. If it did I'd have put it in the description.

**Comment by duduBTW** [comment]
#63 will should fix this
